name: Test Workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Display message
        run: echo "Workflow triggered on commit to dev branch"
